### PR TITLE
Create a Docker build instruction

### PR DESCRIPTION
**Pull request by NobbZ**

### CODE REVIEW

**Comment by NobbZ** [comment]
Please consider this still a WIP, today I learned that there are issues with Erlang on alpine when there is no network. I have already a change for the dockerfile locally, though I haven't been able to commit and push by now due to family reasons. Please do not merge before I push the change to a Ubuntu based image.

**Comment by NobbZ** [comment]
Okay I fixed the base image now and I consider this ready to merge.

**Comment by iHiD** [comment]
I'll merge this so that we can try it. Erik can then check the actual content if required.

**Review by iHiD — APPROVED** [review]

**Comment by iHiD** [comment]
(I've approved it - you can merge @NobbZ )

**Pull request merged**
